import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Toaster } from '@/components/ui/toaster';
import UserContextProvider from '@/context/UserContext.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-customBg ${inter.className}`}>
        <UserContextProvider>
          <main className="h-screen">{children}</main>
          <Toaster />
        </UserContextProvider>
      </body>
    </html>
  );
}
